import { execFileSync } from "node:child_process";
import * as fs from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, expect, test, vi } from "vitest";
import { CONFIG_FILE_NAMES } from "../config/discover-config-file.js";
import { ensureConfigIsTracked } from "./ensure-config-is-tracked.js";

const directories: string[] = [];

afterEach(async () => {
	await Promise.all(
		directories
			.splice(0)
			.map((directory) => fs.rm(directory, { recursive: true, force: true }))
	);
});

test("Git tracks every supported config while ignoring SDK artifacts (#775)", async () => {
	const directory = await fs.mkdtemp(join(tmpdir(), "paraglide-gitignore-"));
	directories.push(directory);
	execFileSync("git", ["init", "--quiet", directory]);
	const projectDir = join(directory, "project.inlang");
	await fs.mkdir(join(projectDir, "cache"), { recursive: true });
	const gitignorePath = join(projectDir, ".gitignore");
	const original = "# Generated by the SDK\r\n*\r\n!settings.json";
	await fs.writeFile(gitignorePath, original);
	for (const name of [
		...CONFIG_FILE_NAMES,
		"settings.json",
		".meta.json",
		"README.md",
		"cache/plugin.js",
	]) {
		await fs.writeFile(join(projectDir, name), "{}");
	}
	await ensureConfigIsTracked({ projectDir, fs });
	expect(await fs.readFile(gitignorePath, "utf8")).toContain(original);
	const tracked = execFileSync(
		"git",
		["ls-files", "--others", "--exclude-standard"],
		{ cwd: directory, encoding: "utf8" }
	)
		.trim()
		.split("\n")
		.sort();
	expect(tracked).toEqual(
		[...CONFIG_FILE_NAMES, "settings.json"]
			.map((name) => `project.inlang/${name}`)
			.sort()
	);

	const appendFile = vi.fn(fs.appendFile);
	await ensureConfigIsTracked({ projectDir, fs: { ...fs, appendFile } });
	expect(appendFile).not.toHaveBeenCalled();

	// A later ignore rule must not cancel the exceptions.
	await fs.appendFile(gitignorePath, "*\n");
	await ensureConfigIsTracked({ projectDir, fs });
	expect(
		execFileSync("git", ["ls-files", "--others", "--exclude-standard"], {
			cwd: directory,
			encoding: "utf8",
		})
	).toContain("project.inlang/paraglide.config.js");
});
